import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import { Grid, GridItem, Spacer, Text, Heading, Box, Tabs, TabList, Tab, TabPanels, TabPanel, Select, Button, Link, Container, Accordion, AccordionButton, AccordionIcon, AccordionPanel, AccordionItem } from '@chakra-ui/react'
import Form1 from '../../components/Form1'
import Form2 from '../../components/Form2'
import Form3 from '../../components/Form3'
import Form4 from '../../components/Form4'
import Form5 from '../../components/Form5'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    return (
        <>
            <Head>
                <title>Forms</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://mscs.dac.gov.in/images/favicon.gif" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Navbar children={undefined} />
                <Box display={'flex'} justifyContent={'center'} minH={'100vh'} width={'100%'} paddingTop={'2%'}>
                    <Accordion allowToggle width={{ base: '100%', md: '50%' }}>
                        <AccordionItem >
                            <h2>
                                <AccordionButton>
                                    <Box as="span" flex='1' textAlign='left'>
                                        CENTRAL REGISTRAR
                                    </Box>
                                    <AccordionIcon />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel pb={4}>
                                <Container centerContent>
                                <Text as='b'>Shri Vijay Kumar,IAS</Text>
                                <Text as='b'>Additional Secretary & Central Registrar of Cooperative Societies</Text>
                                <Text>Ministry of Cooperation,</Text>
                                <Text>Floor-I, Atal Akshay Urja Bhawan,</Text>
                                <Text>Lodhi Road, CGO Complex,</Text>
                                <Text>New Delhi PIN 110 003</Text>
                                <Text>(Landmark : Jawaharlal Nehru Statdium)</Text>
                                </Container>
                            </AccordionPanel>
                        </AccordionItem>
                        <AccordionItem >
                            <h2>
                                <AccordionButton>
                                    <Box as="span" flex='1' textAlign='left'>
                                    DEPUTY SECRETARY
                                    </Box>
                                    <AccordionIcon />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel pb={4}>
                                <Container centerContent>
                                <Text>Shri Kapil Meena, Deputy Secretary</Text>
                                <Text>Ministry of Cooperation,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                </Container>
                            </AccordionPanel>
                        </AccordionItem>
                        <AccordionItem >
                            <h2>
                                <AccordionButton>
                                    <Box as="span" flex='1' textAlign='left'>
                                    DEPUTY COMMISSIONER
                                    </Box>
                                    <AccordionIcon />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel pb={4}>
                                <Container centerContent>
                                    <Text as={'b'}>Shri Jitender Nagar , Deputy Commissioner</Text>
                                <Text>Room No 298</Text>
                                <Text>Ministry of Cooperation,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                </Container>
                            </AccordionPanel>
                        </AccordionItem>
                        <AccordionItem >
                            <h2>
                                <AccordionButton>
                                    <Box as="span" flex='1' textAlign='left'>
                                    ASSISTANT COMMISSIONER
                                    </Box>
                                    <AccordionIcon />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel pb={4}>
                                <Container centerContent>
                                    <Text as={'b'}>Smt. Nisha Sagar, Assistant Commissioner</Text>
                                <Text>Room No 442</Text>
                                <Text>Ministry of Cooperation,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                <Text>Phone : 011-23388911  ext. 4998</Text>
                                <Text>Email-ID : regmscs@gmail.com</Text>
                                </Container>
                            </AccordionPanel>
                        </AccordionItem>
                        <AccordionItem >
                            <h2>
                                <AccordionButton>
                                    <Box as="span" flex='1' textAlign='left'>
                                    UNDER SECRETARY
                                    </Box>
                                    <AccordionIcon />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel pb={4}>
                                <Container centerContent>
                                    <Text as={'b'}>Shri Amit Kumar Rawat, Under secretary</Text>
                                <Text>Ministry of Cooperation,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                </Container>
                            </AccordionPanel>
                        </AccordionItem>
                        <AccordionItem >
                            <h2>
                                <AccordionButton>
                                    <Box as="span" flex='1' textAlign='left'>
                                    DEPUTY DIRECTOR
                                    </Box>
                                    <AccordionIcon />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel pb={4}>
                                <Container centerContent>
                                    <Text as={'b'}>Ms Sucheta Sharma, Deputy Director</Text>
                                <Text>Ministry of Cooperation,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                </Container>
                            </AccordionPanel>
                        </AccordionItem>
                        <AccordionItem >
                            <h2>
                                <AccordionButton>
                                    <Box as="span" flex='1' textAlign='left'>
                                    SECTION OFFICER
                                    </Box>
                                    <AccordionIcon />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel pb={4}>
                                <Container centerContent>
                                    <Text as={'b'}>Shri Rajendra Singh, Section Officer</Text>
                                    <Text as={'b'}>L & M Section</Text>
                                    <Text>Room No 388</Text>
                                <Text>Ministry of Cooperation,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                <Text>Phone :011-23388911 ext 4699/ 4397</Text>
                                <Text>Email ID : lm.section397@gmail.com and regmscs@gmail.com</Text><br /><br />
                                    <Text as={'b'}>Shri Prasant Srivastava, Section Officer</Text>
                                <Text>Ministry of Cooperation,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                </Container>
                            </AccordionPanel>
                        </AccordionItem>
                        <AccordionItem >
                            <h2>
                                <AccordionButton>
                                    <Box as="span" flex='1' textAlign='left'>
                                    SENIOR TECHNICAL ASSISTANT(STA) & SSO
                                    </Box>
                                    <AccordionIcon />
                                </AccordionButton>
                            </h2>
                            <AccordionPanel pb={4}>
                                <Container centerContent>
                                    <Text as={'b'}>Shri Vinay Ginni, Sr. Technical Assistant (Registration)</Text>
                                    <Text>Room No 399-A</Text>
                                <Text>Ministry of Cooperation, Krishi Bhawan,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                <Text>Phone : 011-23388911 ext 4998</Text>
                                <Text>Email: regmscs@gmail.com</Text><br /><br />
                                <Text as={'b'}>Shri Amit Sachdeva, Sr. Technical Assistant (Management)</Text>
                                    <Text>Room No 388</Text>
                                <Text>Ministry of Cooperation, Krishi Bhawan,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                <Text>Phone : 011-23388991 ext 4699/ 4397</Text>
                                <Text>Email-ID :lm.section397@gmail.com</Text><br /><br />
                                <Text as={'b'}>Ms Divya Jain, Senior Statistical Officer (SSO)</Text>
                                    <Text>Room No 388</Text>
                                <Text>Ministry of Cooperation, Krishi Bhawan,</Text>
                                <Text>New Delhi - PIN 110 001</Text>
                                <Text>Phone : 011-23388991 ext 4699/ 4397</Text>
                                <Text>Email-ID :lm.section397@gmail.com</Text><br /><br />
                                </Container>
                            </AccordionPanel>
                        </AccordionItem>
                    </Accordion>
                </Box>
                <Footer />
            </main>
        </>
    )
}
