import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import states from '../../data/states'
import sectors from '../../data/sectors'
import { Grid, GridItem, Spacer, Text, Heading, AccordionPanel, Box, Tabs, TabList, TabPanels, Tab, TabPanel, Select, InputGroup, InputLeftElement, Input, InputLeftAddon, Button, Accordion, AccordionButton, AccordionIcon, AccordionItem } from '@chakra-ui/react';
import {
    FiSearch
} from 'react-icons/fi';
import STable from '../../components/STable'
import sdata, { length } from '../../data/data'
import { useEffect, useState } from 'react'
import { fdatasyncSync } from 'fs'
import YearwiseTable from '../../components/YearwiseTable'
import StatewiseTable from '../../components/StatewiseTable'
import { getFirestore, collection, getDocs } from "firebase/firestore";
import firebase_app from '../../../firebase/config'
const inter = Inter({ subsets: ['latin'] })

interface Data {
    id: string;
    name: string;
    address: string;
    state: string;
    district: string;
    data_of_registration: string;
    area_of_operation: string;
    sector: string;
}

interface MyPageProps {
    data: Data[];
}

export default function Home({ data }: MyPageProps) {
    const [state, setState] = useState<String>('All');
    const [sector, setSector] = useState<String>('All');
    const [search, setSearch] = useState('');
    const [filter_data, setFData] = useState<any>(data)


    const searchData = (name: string) => {
        setFData(data.filter((n: any) => {
            let d = n.name
            return d.toLowerCase().includes(name.toLowerCase());
        }))
    }

    return (
        <>
            <Head>
                <title>Societies</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://mscs.dac.gov.in/images/favicon.gif" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Navbar children={undefined} />
                <Box marginLeft={{ base: 0, md: 60 }} minHeight={'100vh'}>
                    <Box>
                        <Box display={'flex'} padding={4} flexDirection={'row'} alignItems={'start'} justifyContent={'space-between'}>
                            <Box display={'flex'} flexDirection={'row'} width={'100%'} alignItems={'center'}>
                                <Text marginLeft={'4%'}>{filter_data.length} Result(s)</Text>
                            </Box>
                            <InputGroup width={'40%'} display={{ base: 'none', md: 'flex' }}>
                                <InputLeftElement pointerEvents='none'>
                                    <FiSearch color='gray.300' />
                                </InputLeftElement>
                                <Input type='text' placeholder='Search' marginRight={'3%'} onChange={(e) => searchData(e.target.value)} />
                            </InputGroup>
                        </Box>
                        <STable data={filter_data} />
                    </Box></Box>
                <Footer />
            </main>
        </>
    )
}

export const getServerSideProps = async () => {
    const db = getFirestore(firebase_app);
    try {
        const querySnapshot = await getDocs(collection(db, "mscs"));
        let data = querySnapshot.docs.map((doc) => doc.data());
        data = data.filter((item) => item.sector === "Cooperative Bank");

        return {
            props: {
                data,
            },
        };
    } catch (error) {
        console.error('Error fetchingdata:', error);

        return {
            props: {
                data: [],
            },
        };
    }
}