import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import states from '../../data/states'
import sectors from '../../data/sectors'
import { Grid, GridItem, Spacer, Text, Heading, AccordionPanel, Box, Tabs, TabList, TabPanels, Tab, TabPanel, Select, InputGroup, InputLeftAddon, Button, Accordion, AccordionButton, AccordionIcon, AccordionItem } from '@chakra-ui/react';

import STable from '../../components/STable'
import sdata from '../../data/data'
import { useEffect, useState } from 'react'
import { fdatasyncSync } from 'fs'
import YearwiseTable from '../../components/YearwiseTable'
import StatewiseTable from '../../components/StatewiseTable'
import ActsTable from '@/components/ActsTable'
import Checklist from '@/components/Checklist'
import SignupCard from '@/components/SignUp'
import SignIn from '@/components/SignIn'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [state, setState] = useState<String>('All');
    const [sector, setSector] = useState<String>('All');
    const [search, setSearch] = useState('');
    const [data, setData] = useState<any>(sdata)
    const [filter_data, setFData] = useState<any>(data)

    const handleFilter = () => {
        setFData(data.filter((item: any) => {
            const sectorMatch = sector === "All" || item.sector === sector;
            const stateMatch = state === "All" || item.state === state;
            return sectorMatch && stateMatch;
        }))
    }

    return (
        <>
            <Head>
                <title>Account</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://mscs.dac.gov.in/images/favicon.gif" />
                <script src="//code.tidio.co/kdnuococyjb3hivo6vlv2bp68qztldvq.js" async></script>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Navbar children={undefined} />
                <Box marginLeft={{ base: 0, md: 60 }} minHeight={'100vh'}>
                    <SignIn/>
                </Box>
                <Footer />
            </main>
        </>
    )
}
