import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import states from '../../data/states'
import sectors from '../../data/sectors'
import { Grid, GridItem, Spacer, Text, Heading, AccordionPanel, Box, Tabs, TabList, TabPanels, Tab, TabPanel, Select, InputGroup, InputLeftAddon, Button, Accordion, AccordionButton, AccordionIcon, AccordionItem } from '@chakra-ui/react';

import STable from '../../components/STable'
import sdata from '../../data/data'
import { useEffect, useState } from 'react'
import { fdatasyncSync } from 'fs'
import YearwiseTable from '../../components/YearwiseTable'
import StatewiseTable from '../../components/StatewiseTable'
import ActsTable from '@/components/ActsTable'
import Checklist from '@/components/Checklist'
import SignupCard from '@/components/SignUp'
const inter = Inter({ subsets: ['latin'] })

import { useRouter } from 'next/router'
import firebase_app from '../../../firebase/config'
import { getAuth, } from 'firebase/auth'

export default function Home() {
    const router = useRouter();
    const auth = getAuth(firebase_app);
    useEffect(() => {
        // Check if a user is logged in
        const unsubscribe = auth.onAuthStateChanged((user) => {
            if (user) {
                // If the user is not logged in, redirect to the login page
                router.push('/account');
            }
        });

        // Clean up the event listener on unmount
        return () => unsubscribe();
    }, []);

    return (
        <>
            <Head>
                <title>Account</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://mscs.dac.gov.in/images/favicon.gif" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Navbar children={undefined} />
                <Box marginLeft={{ base: 0, md: 60 }} minHeight={'100vh'}>
                    <SignupCard/>
                </Box>
                <Footer />
            </main>
        </>
    )
}
